name: frontend_ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - "frontend/**"

jobs:
  test:
    name: Frontend CI
    runs-on: ubuntu-latest
    # Job間のデータ受け渡しのためだが、ここでは1つのJobなので必要なし
    # outputs:
    #   node-version: ${{ steps.set-node-version.outputs.node-version }}
    env:
      PROJECT_DIR: frontend/
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ env.PROJECT_DIR }}
      - name: Get Node.js version form .node-version
        id: set-node-version
        run: |
          echo "node-version=$(cat .node-version)" >> $GITHUB_OUTPUT
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.set-node-version.outputs.node-version }}
      # TODO: Check cache
      # - name: Check cache
      #   uses: actions/cache@v4
      #   id: node_modules_cache_id
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     path: ${{ env.PROJECT_DIR }}/node_modules
      #     key: ${{ runner.os }}-node-${{ steps.set-node-version.outputs.node-version }}-build-${{ env.cache-name }}-${{ hashFiles(format('{0}/pnpm-lock.yaml', env.PROJECT_DIR))}}
      #     restore-keys: |
      #       ${{ runner.os }}-node-${{ steps.set-node-version.outputs.node-version }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-node-${{ steps.set-node-version.outputs.node-version }}-build-
      #       ${{ runner.os }}-node-${{ steps.set-node-version.outputs.node-version }}-
      - name: Install packages
        run: npm i
      - name: ESLint
        run: npm run lint
      - name: Type Check
        run: npm run type-check
      - name: Build
        run: |
          npm run build
          # clean up dist
          rm -rf dist
      # TODO: Testing
      # - name: Testing
      #   run: pnpm test-coverage -> pnpm test -- --coverage --verbose --colors
